# the location of the hisat2 index (it will be generated if it does
# not exist)
metadir: "/meta"

# the location of the fasta and gtf files relative to the `metadir`.
# If not specified the first available fasta/gtf files in the
# `metadir` will be used

# fasta: ""
# gtf: ""

# mode: "auto"

# see http://www.usadellab.org/cms/?page=trimmomatic for details
trimmer:
  - "LEADING:3"
  - "TRAILING:3"
  - "SLIDINGWINDOW:4:20"
  - "MINLEN:10"
  - "ILLUMINACLIP:NexteraPE-PE.fa:2:30:10"
